### ISSUE TITLE
RuntimeError: Maximum recursion depth exceeded

### ISSUE THREAD

**Issue by zredlined** [larsmaaloee/deep-belief-nets-for-topic-modeling#3]
Hello- I have been trying to get familiar with your code and ran into the following error running example2 and example1 on both Mac OS X (10.9) and Ubuntu 14.04 clients (below) when it's trying to output results in the visualization function. Any ideas what could be happening?

Thanks!

...
Evaluate 7 nearest neighbors.
Correct: 89.9% of 1000
Correct: 90.7% of 2000
Correct: 90.7% of 3000
Evaluate 15 nearest neighbors.
Correct: 89.2% of 1000
Correct: 89.7% of 2000
Correct: 89.4% of 3000
Eval[1]: 93.03%
Eval[3]: 91.69%
Eval[7]: 90.63%
Eval[15]: 89.41%
Outputting test scores to output folder.
Traceback (most recent call last):
  File "main.py", line 213, in <module>
    run_examples()
  File "main.py", line 208, in run_examples
    example2()
  File "main.py", line 161, in example2
    v.visualise_data_pca_2d(input_data=False, number_of_components=4)
  File "/Users/redlined/Desktop/dev/DBN/deep-belief-nets-for-topic-modeling/Testing/visualise.py", line 172, in visualise_data_pca_2d
    self.legend)
  File "/Users/redlined/Desktop/dev/DBN/deep-belief-nets-for-topic-modeling/Testing/pca.py", line 65, in pca_2d
    markersize=6)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/axes.py", line 4137, in plot
    for line in self._get_lines(_args, *_kwargs):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/axes.py", line 317, in _grab_next_args
    for seg in self._plot_args(remaining, kwargs):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/axes.py", line 295, in _plot_args
    x, y = self._xy_from_xy(x, y)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/axes.py", line 213, in _xy_from_xy
    bx = self.axes.xaxis.update_units(x)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/axis.py", line 1336, in update_units
    converter = munits.registry.get_converter(data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/units.py", line 148, in get_converter
    converter = self.get_converter(xravel[0])
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/units.py", line 148, in get_converter
    converter = self.get_converter(xravel[0])
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/units.py", line 148, in get_converter
    converter = self.get_converter(xravel[0])
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/units.py", line 148, in get_converter
    converter = self.get_converter(xravel[0])
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/units.py", line 148, in get_converter
    converter = self.get_converter(xravel[0])
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/numpy/matrixlib/defmatrix.py", line 316, in __getitem__
    out = N.ndarray.**getitem**(self, index)
RuntimeError: maximum recursion depth exceeded

**Comment by zredlined** [comment]
Update: Fixed by upgrading matplotlib and setting dateutil to v2.2!

  534  sudo pip install matplotlib --upgrade
  540  sudo pip uninstall python-dateutil
  541  sudo pip install python-dateutil==2.2
