### ISSUE TITLE
Error in get_attributes

### ISSUE THREAD

**Issue by vikaschib7** [larsmaaloee/deep-belief-nets-for-topic-modeling#9]
Number of documents must be greater than batchsize. Please revise the batchsize.
Dataprocessing ended with an error.
Traceback (most recent call last):
  File "main.py", line 200, in <module>
    run_examples()
  File "main.py", line 194, in run_examples
    example1()
  File "main.py", line 55, in example1
    trainingset_attributes=data_processing.get_attributes())
  File "/home/glmr/anaconda3/apps/deep-belief-nets-for-topic-modeling/DataPreparation/data_processing.py", line 437, in get_attributes
    return s.load(open(env_paths.get_attributes_path(training), "rb"))
IOError: [Errno 2] No such file or directory: 'output/train/BOWs/attributes.p'

**Comment by saria85** [comment]
did you find a solution?
